import type { Metadata } from "next";
import "./globals.css";
import SplashCursor from "@/components/SplashCursor";

import localFont from 'next/font/local'
import Footer from "@/components/layout/Footer";

const author = localFont({
  src: [

    {
      path: '../public/fonts/Author_Complete/Author-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Author_Complete/Author-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Author_Complete/Author-Semibold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/Author_Complete/Author-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${author.className} antialiased`}
      >
        <SplashCursor />
        {children}
      </body>
      
      <div className="max-w-6xl mx-auto px-4">
        <Footer />
      </div>
    </html>
  );
}
